
title: Katelyn Beirne
image: https://github.com/KatelynBeirne/KatelynBeirnePortfolio/blob/25dee8d038ec628c6a6da80529408d03da0e753b/pngs/M3.jpg
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
